{{- if .Values.controller.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "koreo.fullname" . }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "koreo.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "koreo.fullname" . }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
