{{- if .Values.controller.rbac.bind_role -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "koreo.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "koreo.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "koreo.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
