apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "koreo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koreo.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
    app.kubernetes.io/version: {{ include "koreo.controller_chart_version_label" . }}
  {{- with .Values.controller.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicas }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "koreo.selectorLabels" (dict "context" . "name" .Values.controller.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "koreo.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 8 }}
        app.kubernetes.io/version: {{ include "koreo.controller_chart_version_label" . }}
        {{- with .Values.controller.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "koreo.controller.serviceAccountName" . }}
      {{- with .Values.controller.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: "{{- include "koreo.image" (dict "context" . "image" .Values.controller.image) }}:{{ default (include "koreo.controller.defaultTag" .) .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: KOREO_NAMESPACE
              {{- if .Values.controller.koreoNamespace }}
              value: {{ .Values.controller.koreoNamespace | quote }}
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
              {{- end }}

            - name: TEMPLATE_NAMESPACE
              {{- if .Values.controller.templateNamespace }}
              value: {{ .Values.controller.templateNamespace | quote }}
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
              {{- end }}

            - name: RESOURCE_NAMESPACE
              {{- if .Values.controller.resourceNamespace }}
              value: {{ .Values.controller.resourceNamespace | quote }}
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
              {{- end }}

            {{- with .Values.controller.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.controller.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.controller.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.controller.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "koreo.selectorLabels" (dict "context" . "name" .Values.controller.name) | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.controller.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
