{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "koreo.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  # Static required permissions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

#   - apiGroups: ["", "extensions", "apps"]
#     resources: ["*"]
#     verbs: ["*"]:
        
  - apiGroups: ["koreo.dev"]
    resources:
      - workflows
      - functions
      - valuefunctions
      - resourcefunctions
      - functiontests
      - resourcetemplates
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Dynamic read-only rules
  {{- range $group, $resources := .Values.rbac.namespace.read_only }}
  - apiGroups: ["{{ $group }}"]
    resources: {{ toYaml $resources | nindent 4 }}
    verbs: ["get", "list", "watch"]
  {{- end }}

  # Dynamic read-write rules
  {{- range $group, $resources := .Values.rbac.namespace.read_write }}
  - apiGroups: ["{{ $group }}"]
    resources: {{ toYaml $resources | nindent 4 }}
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  {{- end }}
{{- end -}}
