{{- if and .Values.ui.enabled .Values.ui.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "koreo.ui.fullname" . }}-{{ .Release.Namespace }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  {{- range $group, $resources := .Values.ui.rbac.cluster.read_only }}
  - apiGroups: ["{{ $group }}"]
    resources:
{{ toYaml $resources | indent 4 }}
    verbs: ["get", "list", "watch"]
  {{- end }}

  {{- if .Values.development }}
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  {{- end }}
{{- end }}
