{{ if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "koreo.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koreo.labels" (dict "context" . "component" .Values.ui.name "name" .Values.ui.name) | nindent 4 }}
    app.kubernetes.io/version: {{ include "koreo.ui_chart_version_label" . }}
  {{- with .Values.ui.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.ui.replicas }}
  revisionHistoryLimit: {{ .Values.ui.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "koreo.selectorLabels" (dict "context" . "name" .Values.ui.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "koreo.labels" (dict "context" . "component" .Values.ui.name "name" .Values.ui.name) | nindent 8 }}
        app.kubernetes.io/version: {{ include "koreo.ui_chart_version_label" . }}
        {{- with .Values.ui.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "koreo.ui.serviceAccountName" . }}
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: ui
          image: "{{- include "koreo.image" (dict "context" . "image" .Values.ui.image) }}:{{ default (include "koreo.ui.defaultTag" .) .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          {{- with .Values.ui.extraEnv }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.ui.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.ui.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "koreo.selectorLabels" (dict "context" . "name" .Values.ui.name) | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.ui.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
{{- end -}}
