{{- if and .Values.ui.enabled .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ui.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "koreo.labels" (dict "context" $ "component" .Values.ui.name "name" .Values.ui.name) | nindent 4 -}}
  {{- with .Values.ui.serviceAccount.labels  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ui.serviceAccount.pullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
