name: Test Kubernetes Controller with Helm

on:
  push:
    branches:
      - "**" # Runs on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade --install koreo ./charts/koreo --set image.tag=v0.1.x

      - name: Wait for Controller to Be Ready
        run: kubectl wait --for=condition=available --timeout=90s deployment/koreo

      - name: Run Tests (Optional)
        run: |
          # Example: Apply a test CRD and verify behavior
          kubectl apply -f test/test-crd.yaml
          sleep 10  # Allow time for processing
          kubectl get crds

      - name: Cleanup
        if: always()
        run: kind delete cluster --name test-cluster
